version: '3.9'

services:

  postgres:
    container_name: postgres
    restart: always
    image: postgres:14.4
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=ektimo
    ports:
      - 5545:5432
  
  ekitmo-api:
    build: .
    container_name: ektimo-api
    restart: always
    image: ektimo-api
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DATABASE=ektimo
    ports:
      - 8384:8080
    depends_on:
      - postgres

volumes:
  db-data:
