// Code generated by entc, DO NOT EDIT.

package textquestion

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the textquestion type in the database.
	Label = "text_question"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldHumanID holds the string denoting the human_id field in the database.
	FieldHumanID = "human_id"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// FieldAnswer holds the string denoting the answer field in the database.
	FieldAnswer = "answer"
	// Table holds the table name of the textquestion in the database.
	Table = "text_questions"
)

// Columns holds all SQL columns for textquestion fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldHumanID,
	FieldText,
	FieldAnswer,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// HumanIDValidator is a validator for the "human_id" field. It is called by the builders before save.
	HumanIDValidator func(string) error
	// TextValidator is a validator for the "text" field. It is called by the builders before save.
	TextValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
