// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TextQuestionsColumns holds the columns for the "text_questions" table.
	TextQuestionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "human_id", Type: field.TypeString, Unique: true},
		{Name: "text", Type: field.TypeString},
		{Name: "answer", Type: field.TypeString, Nullable: true},
	}
	// TextQuestionsTable holds the schema information for the "text_questions" table.
	TextQuestionsTable = &schema.Table{
		Name:       "text_questions",
		Columns:    TextQuestionsColumns,
		PrimaryKey: []*schema.Column{TextQuestionsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TextQuestionsTable,
	}
)

func init() {
}
