// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/auxcube/ektimo-api/ent/candidate"
	"github.com/auxcube/ektimo-api/ent/schema"
	"github.com/auxcube/ektimo-api/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	candidateFields := schema.Candidate{}.Fields()
	_ = candidateFields
	// candidateDescID is the schema descriptor for id field.
	candidateDescID := candidateFields[0].Descriptor()
	// candidate.DefaultID holds the default value on creation for the id field.
	candidate.DefaultID = candidateDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[0].Descriptor()
	// user.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	user.AgeValidator = userDescAge.Validators[0].(func(int) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
}
