// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/auxcube/ektimo-api/ent/predicate"
	"github.com/auxcube/ektimo-api/ent/textquestion"
)

// TextQuestionDelete is the builder for deleting a TextQuestion entity.
type TextQuestionDelete struct {
	config
	hooks    []Hook
	mutation *TextQuestionMutation
}

// Where appends a list predicates to the TextQuestionDelete builder.
func (tqd *TextQuestionDelete) Where(ps ...predicate.TextQuestion) *TextQuestionDelete {
	tqd.mutation.Where(ps...)
	return tqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tqd *TextQuestionDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tqd.hooks) == 0 {
		affected, err = tqd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TextQuestionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tqd.mutation = mutation
			affected, err = tqd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tqd.hooks) - 1; i >= 0; i-- {
			if tqd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tqd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tqd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tqd *TextQuestionDelete) ExecX(ctx context.Context) int {
	n, err := tqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tqd *TextQuestionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: textquestion.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: textquestion.FieldID,
			},
		},
	}
	if ps := tqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, tqd.driver, _spec)
}

// TextQuestionDeleteOne is the builder for deleting a single TextQuestion entity.
type TextQuestionDeleteOne struct {
	tqd *TextQuestionDelete
}

// Exec executes the deletion query.
func (tqdo *TextQuestionDeleteOne) Exec(ctx context.Context) error {
	n, err := tqdo.tqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{textquestion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tqdo *TextQuestionDeleteOne) ExecX(ctx context.Context) {
	tqdo.tqd.ExecX(ctx)
}
