// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/auxcube/ektimo-api/ent/textquestion"
	"github.com/google/uuid"
)

// TextQuestionCreate is the builder for creating a TextQuestion entity.
type TextQuestionCreate struct {
	config
	mutation *TextQuestionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (tqc *TextQuestionCreate) SetCreatedAt(t time.Time) *TextQuestionCreate {
	tqc.mutation.SetCreatedAt(t)
	return tqc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tqc *TextQuestionCreate) SetNillableCreatedAt(t *time.Time) *TextQuestionCreate {
	if t != nil {
		tqc.SetCreatedAt(*t)
	}
	return tqc
}

// SetUpdatedAt sets the "updated_at" field.
func (tqc *TextQuestionCreate) SetUpdatedAt(t time.Time) *TextQuestionCreate {
	tqc.mutation.SetUpdatedAt(t)
	return tqc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tqc *TextQuestionCreate) SetNillableUpdatedAt(t *time.Time) *TextQuestionCreate {
	if t != nil {
		tqc.SetUpdatedAt(*t)
	}
	return tqc
}

// SetHumanID sets the "human_id" field.
func (tqc *TextQuestionCreate) SetHumanID(s string) *TextQuestionCreate {
	tqc.mutation.SetHumanID(s)
	return tqc
}

// SetText sets the "text" field.
func (tqc *TextQuestionCreate) SetText(s string) *TextQuestionCreate {
	tqc.mutation.SetText(s)
	return tqc
}

// SetAnswer sets the "answer" field.
func (tqc *TextQuestionCreate) SetAnswer(s string) *TextQuestionCreate {
	tqc.mutation.SetAnswer(s)
	return tqc
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (tqc *TextQuestionCreate) SetNillableAnswer(s *string) *TextQuestionCreate {
	if s != nil {
		tqc.SetAnswer(*s)
	}
	return tqc
}

// SetID sets the "id" field.
func (tqc *TextQuestionCreate) SetID(u uuid.UUID) *TextQuestionCreate {
	tqc.mutation.SetID(u)
	return tqc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tqc *TextQuestionCreate) SetNillableID(u *uuid.UUID) *TextQuestionCreate {
	if u != nil {
		tqc.SetID(*u)
	}
	return tqc
}

// Mutation returns the TextQuestionMutation object of the builder.
func (tqc *TextQuestionCreate) Mutation() *TextQuestionMutation {
	return tqc.mutation
}

// Save creates the TextQuestion in the database.
func (tqc *TextQuestionCreate) Save(ctx context.Context) (*TextQuestion, error) {
	var (
		err  error
		node *TextQuestion
	)
	tqc.defaults()
	if len(tqc.hooks) == 0 {
		if err = tqc.check(); err != nil {
			return nil, err
		}
		node, err = tqc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TextQuestionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tqc.check(); err != nil {
				return nil, err
			}
			tqc.mutation = mutation
			if node, err = tqc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tqc.hooks) - 1; i >= 0; i-- {
			if tqc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tqc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tqc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tqc *TextQuestionCreate) SaveX(ctx context.Context) *TextQuestion {
	v, err := tqc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tqc *TextQuestionCreate) Exec(ctx context.Context) error {
	_, err := tqc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tqc *TextQuestionCreate) ExecX(ctx context.Context) {
	if err := tqc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tqc *TextQuestionCreate) defaults() {
	if _, ok := tqc.mutation.CreatedAt(); !ok {
		v := textquestion.DefaultCreatedAt()
		tqc.mutation.SetCreatedAt(v)
	}
	if _, ok := tqc.mutation.UpdatedAt(); !ok {
		v := textquestion.DefaultUpdatedAt()
		tqc.mutation.SetUpdatedAt(v)
	}
	if _, ok := tqc.mutation.ID(); !ok {
		v := textquestion.DefaultID()
		tqc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tqc *TextQuestionCreate) check() error {
	if _, ok := tqc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TextQuestion.created_at"`)}
	}
	if _, ok := tqc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TextQuestion.updated_at"`)}
	}
	if _, ok := tqc.mutation.HumanID(); !ok {
		return &ValidationError{Name: "human_id", err: errors.New(`ent: missing required field "TextQuestion.human_id"`)}
	}
	if v, ok := tqc.mutation.HumanID(); ok {
		if err := textquestion.HumanIDValidator(v); err != nil {
			return &ValidationError{Name: "human_id", err: fmt.Errorf(`ent: validator failed for field "TextQuestion.human_id": %w`, err)}
		}
	}
	if _, ok := tqc.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "TextQuestion.text"`)}
	}
	if v, ok := tqc.mutation.Text(); ok {
		if err := textquestion.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "TextQuestion.text": %w`, err)}
		}
	}
	return nil
}

func (tqc *TextQuestionCreate) sqlSave(ctx context.Context) (*TextQuestion, error) {
	_node, _spec := tqc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tqc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (tqc *TextQuestionCreate) createSpec() (*TextQuestion, *sqlgraph.CreateSpec) {
	var (
		_node = &TextQuestion{config: tqc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: textquestion.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: textquestion.FieldID,
			},
		}
	)
	if id, ok := tqc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tqc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: textquestion.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := tqc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: textquestion.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := tqc.mutation.HumanID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: textquestion.FieldHumanID,
		})
		_node.HumanID = value
	}
	if value, ok := tqc.mutation.Text(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: textquestion.FieldText,
		})
		_node.Text = value
	}
	if value, ok := tqc.mutation.Answer(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: textquestion.FieldAnswer,
		})
		_node.Answer = value
	}
	return _node, _spec
}

// TextQuestionCreateBulk is the builder for creating many TextQuestion entities in bulk.
type TextQuestionCreateBulk struct {
	config
	builders []*TextQuestionCreate
}

// Save creates the TextQuestion entities in the database.
func (tqcb *TextQuestionCreateBulk) Save(ctx context.Context) ([]*TextQuestion, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tqcb.builders))
	nodes := make([]*TextQuestion, len(tqcb.builders))
	mutators := make([]Mutator, len(tqcb.builders))
	for i := range tqcb.builders {
		func(i int, root context.Context) {
			builder := tqcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TextQuestionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tqcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tqcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tqcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tqcb *TextQuestionCreateBulk) SaveX(ctx context.Context) []*TextQuestion {
	v, err := tqcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tqcb *TextQuestionCreateBulk) Exec(ctx context.Context) error {
	_, err := tqcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tqcb *TextQuestionCreateBulk) ExecX(ctx context.Context) {
	if err := tqcb.Exec(ctx); err != nil {
		panic(err)
	}
}
