// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TextQuestion is the predicate function for textquestion builders.
type TextQuestion func(*sql.Selector)
